# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: units.tsv

ref:
    # gtf file with transcripts
    annotation: "/home/tdidomenico/projects/bollito_data/genome/gencode.vM20.annotation.gtf"
    sequence: "/home/tdidomenico/projects/bollito_data/genome/GRCm38.primary_assembly.genome.fa"

whitelist: "res/whitelists/3M-february-2018.txt"

params:
    star: "--soloType Droplet --soloFeatures Gene --outFilterMultimapNmax 50 --winAnchorMultimapNmax 50 --alignEndsType EndToEnd --outReadsUnmapped Fastx --soloUMIlen 12 --outSAMtype BAM SortedByCoordinate"
    cutadapt: "-G GCAGTGGTATCAACGCAGAGTACATGGG -m 16"

